//
// Copyright Coinbase, Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package common

import (
	"github.com/dB2510/kryptology/pkg/core/curves"
)

// Challenge generated by fiat-shamir heuristic
type Challenge = curves.Scalar
